### PR TITLE
fix: update CustomerService add refreshToken 2025-05-25 17:21:20

### LINKED ISSUE #108: update CustomService add refresh tocken

### PR DESCRIPTION
**Pull request by weekden**
# Description

Update CustomerService

## Related Task

Closes #108 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration
- [x] Code refactoring
- [ ] Documentation
- [ ] Other:

## What was done?

*   Scripts added:
*  added AuthController
*   refactor code
*   added loginWithRefreshToken and opportunity to save cache token in session storage

## Author's Checklist

- [x] My code follows the style guidelines of this project (ESLint / Prettier)
- [x] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have made corresponding changes to the documentation
- [x] The PR title is clear and reflects the changes
- [x] The PR is targeted to the correct branch (`release/catalog-product-profile`)

### CODE REVIEW

File: src/models/services/AuthService.ts [hunk 1]
```diff
@@ -4,25 +4,43 @@ import {
...
   ByProjectKeyRequestBuilder,
   createApiBuilderFromCtpClient,
+  Customer,
   CustomerSignInResult,
 } from '@commercetools/platform-sdk';
 import type { CustomerDraftBody, CustomerLoginData } from '../types/api-types';
+import { REFRESH_TOKEN } from '../../controllers/AuthController';
+
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+const tokenCache: any = {
```
Comment (tanyagoryaninaD) [inline src/models/services/AuthService.ts:21]: Можно ли реализовать без any?

Comment (weekden) [reply src/models/services/AuthService.ts:21]: Пока предлагаю оставить так, чтоб не терялся токен. До конца спринта решим эту проблему

**Review by tanyagoryaninaD — APPROVED** [review]
